[credentials]
username = "maverickseneris@gmail.com"
password = "4040811#Mav"

[theme]
background = "#282828"
primary = "#ebdbb2"
secondary = "#d79921"
title = "#fb4934"
playing = "#fb4934"
playing_bg = "#282828"
highlight = "#ebdbb2"
highlight_bg = "#665c54"
playing_selected = "#b8bb26"
error = "#282828"
error_bg = "#fb4934"
statusbar = "#fabd2f"
statusbar_bg = "#3c3836"
statusbar_progress = "#458588"
cmdline = "#fabd2f"
cmdline_bg = "#1d2021"

# --- Old Catppuccin Theme ---
# background = "#1e1e2e"
# primary = "#cdd6f4"
# secondary = "#94e2d5"
# title = "#89b4fa"
# playing = "#a6e3a1"
# playing_bg = "#1e1e2e"
# highlight = "#cdd6f4"
# highlight_bg = "#536994"
# playing_selected = "#a6e3a1"
# error = "#1e1e2e"
# error_bg = "#f38ba8"
# statusbar = "#89b4fa"
# statusbar_bg = "#313244"
# statusbar_progress = "#89b4fa"
# cmdline = "#89b4fa"
# cmdline_bg = "#181825"

